services:
  db:
    image: ankane/pgvector:latest
    container_name: gabarita_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gabarita_ai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:alpine
    container_name: gabarita_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: